package frames;

import com.nanoka.integrador1.models.AvailableQuantity;
import com.nanoka.integrador1.models.Material;
import com.nanoka.integrador1.models.Supply;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class SupplyForm extends javax.swing.JDialog {
    
    private final QuantityMaterials quantityMaterials;
    private final int row;

    public SupplyForm(QuantityMaterials parent, boolean modal) {
        super(parent, modal);
        this.quantityMaterials = parent;
        this.row = -1;
        
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Agregar Insumo");
        
        btn_add_supply.setEnabled(false);
        this.addTextFieldValidator();
    }
    
    public SupplyForm(QuantityMaterials parent, boolean modal, int row, ArrayList<Double> quantityByMaterial, AvailableQuantity availableQuantity) {
        super(parent, modal);
        this.quantityMaterials = parent;
        this.row = row;
        
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Editar Insumo");
        
        this.FillFields(quantityByMaterial, availableQuantity);
        this.ModifyUpdateButton();
        this.addTextFieldValidator();
    }
    
    private void addTextFieldValidator() {
        addValidator(txt_name);
        addValidator(txt_quantity_a);
        addValidator(txt_quantity_b);
        addValidator(txt_quantity_available);
    }
    
    private void ModifyUpdateButton() {
       btn_add_supply.setText("Editar");
       btn_add_supply.setBackground(Color.yellow);
       btn_add_supply.setForeground(Color.black);
    }
    
    private void FillFields(ArrayList<Double> suppliesByMaterial, AvailableQuantity availableQuantity) {
        txt_name.setText(availableQuantity.getName());
        txt_quantity_a.setText(suppliesByMaterial.get(0).toString());
        txt_quantity_b.setText(suppliesByMaterial.get(1).toString());
        txt_quantity_available.setText(availableQuantity.getAvailable().toString());
    }
    
    private void addValidator(JTextField textField) {
        textField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validateInputs();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateInputs();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateInputs();
            }

        });
    }
    
    private void validateInputs() {
        boolean isValid = !txt_name.getText().isBlank() &&
                                    !txt_quantity_a.getText().isBlank() &&
                                    !txt_quantity_b.getText().isBlank() &&
                                    !txt_quantity_available.getText().isBlank();
        btn_add_supply.setEnabled(isValid);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add_supply = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_quantity_a = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_quantity_b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_quantity_available = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_add_supply.setBackground(new java.awt.Color(0, 153, 0));
        btn_add_supply.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_supply.setText("Agregar");
        btn_add_supply.setPreferredSize(new java.awt.Dimension(90, 25));
        btn_add_supply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_supplyActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Cantidad para el material A:");

        txt_quantity_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quantity_aKeyTyped(evt);
            }
        });

        jLabel4.setText("Cantidad para el material B:");

        txt_quantity_b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quantity_bKeyTyped(evt);
            }
        });

        jLabel5.setText("Cantidad disponible:");

        txt_quantity_available.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quantity_availableKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add_supply, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_quantity_b)
                            .addComponent(txt_quantity_available)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_quantity_a))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_name)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_quantity_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_quantity_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_quantity_available, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_supply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_add_supplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_supplyActionPerformed
        String name = txt_name.getText();
        ArrayList<Double> supplies = new ArrayList<>();
        supplies.add(Double.valueOf(txt_quantity_a.getText()));
        supplies.add(Double.valueOf(txt_quantity_b.getText()));
        Double available = Double.valueOf(txt_quantity_available.getText());
        AvailableQuantity availableQuantity = new AvailableQuantity(name, available);
        if(this.row == -1) {
            this.quantityMaterials.supplyTable.addRow(supplies, availableQuantity);
        }else {
            this.quantityMaterials.supplyTable.updateRow(this.row, supplies,availableQuantity);
        }
        dispose();
        this.quantityMaterials.validateInputs();
    }//GEN-LAST:event_btn_add_supplyActionPerformed

    private void txt_quantity_aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantity_aKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_quantity_aKeyTyped

    private void txt_quantity_bKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantity_bKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_quantity_bKeyTyped

    private void txt_quantity_availableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantity_availableKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_quantity_availableKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SupplyForm dialog = new SupplyForm(new QuantityMaterials(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_supply;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_quantity_a;
    private javax.swing.JTextField txt_quantity_available;
    private javax.swing.JTextField txt_quantity_b;
    // End of variables declaration//GEN-END:variables
}
